name: 'Nuclesus_Vulnerability_Report'
description: 'Get Vulns from Nuclesus'
inputs:
  NUCLEUS_API_ENDPOINT:
    description: 'Nucleus API Endpoint'
    required: true
    default: 'https://nucleus-us3.nucleussec.com/nucleus/api'
  NUCLEUS_API_KEY:
    description: 'Nucleus API Key'
    required: true
  NUCLEUS_PROJECT_GROUP:
    description: 'Nucleus Project Group'  
    required: true
  NUCLEUS_PROJECT_ID:
    description: 'Nucleus Project ID'
    required: true
  NUCLEUS_DATAFOLDER:
    description: 'Nucleus Datafolder'
    required: true
  LOGLEVEL:
    description: 'Log Level'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install dependencies
      run: |
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: sh
    - name: Run script file
      run: |
        python3 $GITHUB_ACTION_PATH/getVulns.py
      shell: sh
    - name: list files from data folder
      run: |
        ls -lag $GITHUB_WORKSPACE/
        ls -lag $GITHUB_WORKSPACE/$NUCLEUS_DATAFOLDER/
      shell: sh