# action.yml
name: 'get-nucleus-vulns'
description: 'Retrieve asset vulnerabilities from Nucleus'
inputs:
  NUCLEUS_API_KEY:
    description: 'Nucleus Auth Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.NUCLEUS_API_KEY }}