# action.yml
name: 'get-nucleus-vulns'
description: 'Retrieve asset vulnerabilities from Nucleus'
inputs:
  NUCLEUS_API_KEY:
    description: 'Nucleus Auth Token'
    required: true
  NUCLEUS_ASSET_GROUP:
    description: 'Nucleus Asset Group'
    required: true
  NUCLEUS_PROJECT_ID:
    description: 'Nucleus Project ID'
    required: true
  NUCLEUS_DATAFOLDER:
    description: 'Nucleus Datafolder'
    required: false
  NUCLEUS_API_ENDPOINT:
    description: 'Nucleus API Endpoint'
    required: false
  LOGLEVEL:
    description: 'Log Level'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.NUCLEUS_API_KEY }}
    - ${{ inputs.NUCLEUS_ASSET_GROUP }}
    - ${{ inputs.NUCLEUS_PROJECT_ID }}
    - ${{ inputs.NUCLEUS_DATAFOLDER }}
    - ${{ inputs.NUCLEUS_API_ENDPOINT }}
    - ${{ inputs.LOGLEVEL }}

branding:
  icon: 'shield'
  color: 'blue'