on: 
  workflow_dispatch:
  push:
jobs:
  retrieve-nucleus-vulns:
    name: Nucleus_Vulnerability_Report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NUCLEUS_API_KEY: ${{ secrets.NUCLEUS_API_KEY }}
      NUCLEUS_ASSET_GROUP: '/Product Name/Cybersecurity Incident Response'
      NUCLEUS_PROJECT_ID: '13000008'
      NUCLEUS_API_ENDPOINT: 'https://nucleus-us3.nucleussec.com/nucleus/api'
      NUCLEUS_DATAFOLDER: './'
      LOGLEVEL: 'warning'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Vulns
        id: get-nucleus-vulns
        continue-on-error: false
        timeout-minutes: 5
        uses: ./

      - name: Commit results to Github
        id: commit-results
        continue-on-error: false
        timeout-minutes: 1
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --force .
          git commit -m "🤖 [Github Action]: Saved vulnerabilities details"
          git push origin main
