on: [push]

jobs:
  retrieve-nucleus-vulns:
    runs-on: ubuntu-latest
    env:
      NUCLEUS_API_ENDPOINT: "https://nucleus-us3.nucleussec.com/nucleus/api"
      NUCLEUS_PROJECT_GROUP: "/Product Name/Cybersecurity Incident Response"
      NUCLEUS_DATAFOLDER: "data"
      NUCLEUS_PROJECT_ID: "13000008"
      NUCLEUS_API_KEY: ${{ secrets.NUCLEUS_API_KEY }}
      LOGLEVEL: ${{ secrets.LOGLEVEL }}
    name: Retrieve Vulns from Nucleus
    steps:
      - name: Get Vulns
        id: get-vulns
        uses: samkshah/nucleus@v1
