on: 
  workflow_dispatch:
  push:

jobs:
  retrieve-nucleus-vulns:
    name: Nucleus_Vulnerability_Report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Vulns
        uses: ./
        with:
            NUCLEUS_PROJECT_GROUP: "/Product Name/Cybersecurity Incident Response"
            NUCLEUS_API_KEY: ${{ secrets.NUCLEUS_API_KEY }}
            LOGLEVEL: "INFO"